Repository openbuildxyz/Web3-Frontend-Bootcamp, pull requests merged in 2024-06, with the labels that each got.

#185 task1: sheldon-xc
  members/sheldon-xc/task1/.eslintrc.cjs
  members/sheldon-xc/task1/index.html
  members/sheldon-xc/task1/package-lock.json
  members/sheldon-xc/task1/package.json
  members/sheldon-xc/task1/public/react.svg
  members/sheldon-xc/task1/public/vite.svg
  members/sheldon-xc/task1/src/App.css
  members/sheldon-xc/task1/src/App.tsx
  members/sheldon-xc/task1/src/assets/react.svg
  members/sheldon-xc/task1/src/components/AddToDo.tsx
  members/sheldon-xc/task1/src/components/Header.tsx
  members/sheldon-xc/task1/src/components/ToDoItem.tsx
  members/sheldon-xc/task1/src/components/ToDoList.tsx
  members/sheldon-xc/task1/src/main.tsx
  members/sheldon-xc/task1/src/vite-env.d.ts
  members/sheldon-xc/task1/tsconfig.json
  members/sheldon-xc/task1/tsconfig.node.json
  members/sheldon-xc/task1/types/todo.d.ts
  members/sheldon-xc/task1/vite.config.ts
Labels: invalid

#152 feat: task 1
  members/miawithcode/readme.md
Labels: invalid

#444 task1: WangEn
  members/WangEn/task1/.eslintrc.cjs
  members/WangEn/task1/index.html
  members/WangEn/task1/package.json
  members/WangEn/task1/pnpm-lock.yaml
  members/WangEn/task1/public/vite.svg
  members/WangEn/task1/readme.md
  members/WangEn/task1/src/App.css
  members/WangEn/task1/src/App.tsx
  members/WangEn/task1/src/TodoList.css
  members/WangEn/task1/src/assets/react.svg
  members/WangEn/task1/src/components/AddToDo.tsx
  members/WangEn/task1/src/components/Footer.tsx
  members/WangEn/task1/src/components/Header.tsx
  members/WangEn/task1/src/components/TodoItem.tsx
  members/WangEn/task1/src/components/TodoList.tsx
  members/WangEn/task1/src/index.css
  members/WangEn/task1/src/main.tsx
  members/WangEn/task1/src/vite-env.d.ts
  members/WangEn/task1/tsconfig.json
  members/WangEn/task1/tsconfig.node.json
  members/WangEn/task1/vite.config.ts
Labels: invalid

#434 task1: lulu546
  members/lulu546/task1/.eslintrc.cjs
  members/lulu546/task1/.gitignore
  members/lulu546/task1/README.md
  members/lulu546/task1/api.ts
  members/lulu546/task1/index.html
  members/lulu546/task1/package-lock.json
  members/lulu546/task1/package.json
  members/lulu546/task1/postcss.config.js
  members/lulu546/task1/public/vite.svg
  members/lulu546/task1/src/App.tsx
  members/lulu546/task1/src/assets/react.svg
  members/lulu546/task1/src/components/AddTask.tsx
  members/lulu546/task1/src/components/Header.tsx
  members/lulu546/task1/src/components/Modal.tsx
  members/lulu546/task1/src/components/ToDoItem.tsx
  members/lulu546/task1/src/components/TodoList.tsx
  members/lulu546/task1/src/globals.css
  members/lulu546/task1/src/index.css
  members/lulu546/task1/src/main.tsx
  members/lulu546/task1/src/output.css
  members/lulu546/task1/src/store/index.ts
  members/lulu546/task1/src/vite-env.d.ts
  members/lulu546/task1/tailwind.config.ts
  members/lulu546/task1/tsconfig.json
  members/lulu546/task1/tsconfig.node.json
  members/lulu546/task1/types/tasks.ts
  members/lulu546/task1/vite.config.ts
  members/lulu546/task1/yarn.lock
Labels: bug

#219 task1: TomatoDroid
  members/TomatoDroid/task1/readme.md
  members/TomatoDroid/task1/todo-list/.gitignore
  members/TomatoDroid/task1/todo-list/.npmrc
  members/TomatoDroid/task1/todo-list/README.md
  members/TomatoDroid/task1/todo-list/index.html
  members/TomatoDroid/task1/todo-list/package.json
  members/TomatoDroid/task1/todo-list/pnpm-lock.yaml
  members/TomatoDroid/task1/todo-list/public/vite.svg
  members/TomatoDroid/task1/todo-list/src/App.css
  members/TomatoDroid/task1/todo-list/src/App.tsx
  members/TomatoDroid/task1/todo-list/src/assets/react.svg
  members/TomatoDroid/task1/todo-list/src/components/AddToDo.tsx
  members/TomatoDroid/task1/todo-list/src/components/CheckBox.css
  members/TomatoDroid/task1/todo-list/src/components/CheckBox.tsx
  members/TomatoDroid/task1/todo-list/src/components/Header.tsx
  members/TomatoDroid/task1/todo-list/src/components/ToDoItem.tsx
  members/TomatoDroid/task1/todo-list/src/components/ToDoList.tsx
  members/TomatoDroid/task1/todo-list/src/composables/useLocalStorage.ts
  members/TomatoDroid/task1/todo-list/src/index.css
  members/TomatoDroid/task1/todo-list/src/main.tsx
  members/TomatoDroid/task1/todo-list/src/types.tsx
  members/TomatoDroid/task1/todo-list/src/vite-env.d.ts
  members/TomatoDroid/task1/todo-list/tsconfig.json
  members/TomatoDroid/task1/todo-list/vite.config.ts
Labels: invalid

#518 init: Arthas0v0
  members/Arthas0v0/readme.md
Labels: bug

#265 task1: barry
  members/haobarry/task1/.gitignore
  members/haobarry/task1/README.md
  members/haobarry/task1/components.json
  members/haobarry/task1/index.html
  members/haobarry/task1/package.json
  members/haobarry/task1/pnpm-lock.yaml
  members/haobarry/task1/postcss.config.js
  members/haobarry/task1/public/vite.svg
  members/haobarry/task1/src/App.css
  members/haobarry/task1/src/App.tsx
  members/haobarry/task1/src/Header.tsx
  members/haobarry/task1/src/ToDoItem.tsx
  members/haobarry/task1/src/ToDoList.tsx
  members/haobarry/task1/src/assets/react.svg
  members/haobarry/task1/src/components/ui/button.tsx
  members/haobarry/task1/src/components/ui/checkbox.tsx
  members/haobarry/task1/src/components/ui/textarea.tsx
  members/haobarry/task1/src/index.css
  members/haobarry/task1/src/lib/utils.ts
  members/haobarry/task1/src/main.tsx
  members/haobarry/task1/src/store.ts
  members/haobarry/task1/src/vite-env.d.ts
  members/haobarry/task1/tailwind.config.js
  members/haobarry/task1/tsconfig.json
  members/haobarry/task1/tsconfig.node.json
  members/haobarry/task1/vite.config.ts
  members/haobarry/task1/效果页.png
Labels: invalid

#415 task1:www759
  members/www759/task1/.eslintrc.cjs
  members/www759/task1/.gitignore
  members/www759/task1/README.md
  members/www759/task1/index.html
  members/www759/task1/package-lock.json
  members/www759/task1/package.json
  members/www759/task1/src/AddToDo.jsx
  members/www759/task1/src/App.css
  members/www759/task1/src/App.jsx
  members/www759/task1/src/Header.jsx
  members/www759/task1/src/ToDoItem.jsx
  members/www759/task1/src/ToDoList.jsx
  members/www759/task1/src/addTodo.css
  members/www759/task1/src/index.css
  members/www759/task1/src/main.jsx
  members/www759/task1/src/todoItem.css
  members/www759/task1/vite.config.js
  members/www759/task1/效果图.png
Labels: invalid

#431 task1: vv1133
  members/vv1133/task1/index.html
  members/vv1133/task1/package.json
  members/vv1133/task1/public/vite.svg
  members/vv1133/task1/src/AddToDo.tsx
  members/vv1133/task1/src/App.css
  members/vv1133/task1/src/App.tsx
  members/vv1133/task1/src/Header.tsx
  members/vv1133/task1/src/ToDoItem.tsx
  members/vv1133/task1/src/ToDoList.tsx
  members/vv1133/task1/src/assets/react.svg
  members/vv1133/task1/src/index.css
  members/vv1133/task1/src/interface.ts
  members/vv1133/task1/src/main.tsx
  members/vv1133/task1/src/vite-env.d.ts
  members/vv1133/task1/task1.png
  members/vv1133/task1/tsconfig.json
  members/vv1133/task1/tsconfig.node.json
  members/vv1133/task1/vite.config.ts
Labels: invalid

#466 task1:choizhang
  members/choizhang/task1/.eslintrc.cjs
  members/choizhang/task1/.gitignore
  members/choizhang/task1/index.html
  members/choizhang/task1/package-lock.json
  members/choizhang/task1/package.json
  members/choizhang/task1/public/vite.svg
  members/choizhang/task1/readme.md
  members/choizhang/task1/src/App.css
  members/choizhang/task1/src/App.tsx
  members/choizhang/task1/src/assets/react.svg
  members/choizhang/task1/src/components/AddToDo.tsx
  members/choizhang/task1/src/components/Header.tsx
  members/choizhang/task1/src/components/ToDoItem.tsx
  members/choizhang/task1/src/components/ToDoList.tsx
  members/choizhang/task1/src/index.css
  members/choizhang/task1/src/main.tsx
  members/choizhang/task1/src/vite-env.d.ts
  members/choizhang/task1/tsconfig.json
  members/choizhang/task1/tsconfig.node.json
  members/choizhang/task1/vite.config.ts
  members/choizhang/task2/readme.md
Labels: invalid

#471 task1
  members/321llljjjfff123/task1/todo_list/.eslintrc.cjs
  members/321llljjjfff123/task1/todo_list/.gitignore
  members/321llljjjfff123/task1/todo_list/README.md
  members/321llljjjfff123/task1/todo_list/index.html
  members/321llljjjfff123/task1/todo_list/package-lock.json
  members/321llljjjfff123/task1/todo_list/package.json
  members/321llljjjfff123/task1/todo_list/public/vite.svg
  members/321llljjjfff123/task1/todo_list/src/App.css
  members/321llljjjfff123/task1/todo_list/src/App.tsx
  members/321llljjjfff123/task1/todo_list/src/assets/react.svg
  members/321llljjjfff123/task1/todo_list/src/components/AddToDo.tsx
  members/321llljjjfff123/task1/todo_list/src/components/Header.tsx
  members/321llljjjfff123/task1/todo_list/src/components/ToDoItem.tsx
  members/321llljjjfff123/task1/todo_list/src/index.css
  members/321llljjjfff123/task1/todo_list/src/main.tsx
  members/321llljjjfff123/task1/todo_list/src/vite-env.d.ts
  members/321llljjjfff123/task1/todo_list/tsconfig.json
  members/321llljjjfff123/task1/todo_list/tsconfig.node.json
  members/321llljjjfff123/task1/todo_list/vite.config.ts
  members/321llljjjfff123/task1/图片.png
Labels: invalid

#496 task1: hundren
  members/hundren/task1/README.md
  members/hundren/task1/index.html
  members/hundren/task1/package.json
  members/hundren/task1/pnpm-lock.yaml
  members/hundren/task1/public/screenshot-todolist-two-blush.vercel.app-2024.06.11-23_56_48.png
  members/hundren/task1/public/vite.svg
  members/hundren/task1/src/AddToDo.tsx
  members/hundren/task1/src/App.css
  members/hundren/task1/src/App.tsx
  members/hundren/task1/src/Header.tsx
  members/hundren/task1/src/ToDoItem.tsx
  members/hundren/task1/src/ToDoList.tsx
  members/hundren/task1/src/assets/react.svg
  members/hundren/task1/src/i.ts
  members/hundren/task1/src/index.css
  members/hundren/task1/src/main.tsx
  members/hundren/task1/src/vite-env.d.ts
  members/hundren/task1/tsconfig.json
  members/hundren/task1/tsconfig.node.json
  members/hundren/task1/vite.config.ts
Labels: bug

#244 task1: caocanx
  members/caocanx/task1/todo-list-app/.gitignore
  members/caocanx/task1/todo-list-app/index.html
  members/caocanx/task1/todo-list-app/package.json
  members/caocanx/task1/todo-list-app/src/App.jsx
  members/caocanx/task1/todo-list-app/src/components/AddToDo.jsx
  members/caocanx/task1/todo-list-app/src/components/Header.jsx
  members/caocanx/task1/todo-list-app/src/components/ToDoItem.jsx
  members/caocanx/task1/todo-list-app/src/components/ToDoList.jsx
  members/caocanx/task1/todo-list-app/src/components/index.js
  members/caocanx/task1/todo-list-app/src/main.jsx
  members/caocanx/task1/todo-list-app/vite.config.js
Labels: bug

#498 task1：Yohohohohohoho
  members/Yahohohohohoho/task1/.eslintrc.cjs
  members/Yahohohohohoho/task1/.gitignore
  members/Yahohohohohoho/task1/README.md
  members/Yahohohohohoho/task1/index.html
  members/Yahohohohohoho/task1/package-lock.json
  members/Yahohohohohoho/task1/package.json
  members/Yahohohohohoho/task1/public/vite.svg
  members/Yahohohohohoho/task1/src/AddToDo.tsx
  members/Yahohohohohoho/task1/src/App.css
  members/Yahohohohohoho/task1/src/App.tsx
  members/Yahohohohohoho/task1/src/Header.tsx
  members/Yahohohohohoho/task1/src/ToDoList.tsx
  members/Yahohohohohoho/task1/src/assets/react.svg
  members/Yahohohohohoho/task1/src/index.css
  members/Yahohohohohoho/task1/src/main.tsx
  members/Yahohohohohoho/task1/src/style.css
  members/Yahohohohohoho/task1/src/vite-env.d.ts
  members/Yahohohohohoho/task1/tsconfig.json
  members/Yahohohohohoho/task1/tsconfig.node.json
  members/Yahohohohohoho/task1/vite.config.ts
Labels: bug

#570 task1:Yaqioooong
  members/Yaqioooong/task1/.eslintrc.cjs
  members/Yaqioooong/task1/.gitignore
  members/Yaqioooong/task1/PixPin_2024-06-13_23-20-09.jpg
  members/Yaqioooong/task1/README.md
  members/Yaqioooong/task1/index.html
  members/Yaqioooong/task1/package-lock.json
  members/Yaqioooong/task1/package.json
  members/Yaqioooong/task1/src/App.css
  members/Yaqioooong/task1/src/App.jsx
  members/Yaqioooong/task1/src/assets/react.svg
  members/Yaqioooong/task1/src/components/AddToDo.jsx
  members/Yaqioooong/task1/src/components/Header.jsx
  members/Yaqioooong/task1/src/components/ToDoItem.jsx
  members/Yaqioooong/task1/src/components/ToDoList.jsx
  members/Yaqioooong/task1/src/index.css
  members/Yaqioooong/task1/src/main.jsx
  members/Yaqioooong/task1/vite.config.js
Labels: bug

#645 init:Ruby He
  members/dreamahouse/readme.md
Labels: bug

#426 task1: chefuny
  members/chefuny/task1/rendering.png
  members/chefuny/task1/todolist/.eslintrc.cjs
  members/chefuny/task1/todolist/README.md
  members/chefuny/task1/todolist/index.html
  members/chefuny/task1/todolist/package-lock.json
  members/chefuny/task1/todolist/package.json
  members/chefuny/task1/todolist/public/vite.svg
  members/chefuny/task1/todolist/src/App.css
  members/chefuny/task1/todolist/src/App.jsx
  members/chefuny/task1/todolist/src/assets/react.svg
  members/chefuny/task1/todolist/src/components/AddToDo.jsx
  members/chefuny/task1/todolist/src/components/Header.jsx
  members/chefuny/task1/todolist/src/components/ToDoItem.jsx
  members/chefuny/task1/todolist/src/components/ToDoList.jsx
  members/chefuny/task1/todolist/src/index.css
  members/chefuny/task1/todolist/src/main.jsx
  members/chefuny/task1/todolist/vite.config.js
Labels: bug

#113 feat: warjiang register
  members/warjiang/readme.md
  members/warjiang/task01/.eslintrc.cjs
  members/warjiang/task01/.gitignore
  members/warjiang/task01/.npmrc
  members/warjiang/task01/README.md
  members/warjiang/task01/index.html
  members/warjiang/task01/package.json
  members/warjiang/task01/pnpm-lock.yaml
  members/warjiang/task01/public/vite.svg
  members/warjiang/task01/src/App.css
  members/warjiang/task01/src/App.tsx
  members/warjiang/task01/src/assets/react.svg
  members/warjiang/task01/src/components/todo/add.tsx
  members/warjiang/task01/src/components/todo/index.tsx
  members/warjiang/task01/src/components/todo/item.tsx
  members/warjiang/task01/src/components/todo/list.tsx
  members/warjiang/task01/src/index.css
  members/warjiang/task01/src/main.tsx
  members/warjiang/task01/src/vite-env.d.ts
  members/warjiang/task01/tsconfig.json
  members/warjiang/task01/tsconfig.node.json
  members/warjiang/task01/vite.config.ts
Labels: bug

#116 feat: 完成task1和完善报名信息
  members/zhuoqinyue/readme.md
  members/zhuoqinyue/task1/.eslintrc.cjs
  members/zhuoqinyue/task1/.gitignore
  members/zhuoqinyue/task1/index.html
  members/zhuoqinyue/task1/package-lock.json
  members/zhuoqinyue/task1/package.json
  members/zhuoqinyue/task1/src/App.css
  members/zhuoqinyue/task1/src/App.tsx
  members/zhuoqinyue/task1/src/assets/close.svg
  members/zhuoqinyue/task1/src/components/addToDo.tsx
  members/zhuoqinyue/task1/src/components/flag.css
  members/zhuoqinyue/task1/src/components/flag.tsx
  members/zhuoqinyue/task1/src/components/footer.tsx
  members/zhuoqinyue/task1/src/components/header.tsx
  members/zhuoqinyue/task1/src/components/index.ts
  members/zhuoqinyue/task1/src/components/toDoItem.tsx
  members/zhuoqinyue/task1/src/components/toDoList.tsx
  members/zhuoqinyue/task1/src/components/todoItem.css
  members/zhuoqinyue/task1/src/components/types.ts
  members/zhuoqinyue/task1/src/index.css
  members/zhuoqinyue/task1/src/main.tsx
  members/zhuoqinyue/task1/src/vite-env.d.ts
  members/zhuoqinyue/task1/tsconfig.json
  members/zhuoqinyue/task1/tsconfig.node.json
  members/zhuoqinyue/task1/vite.config.ts
Labels: bug

#344 task2: gamble369
  members/gamble369/task2/02_Blockchain_Basic.md
  members/gamble369/task2/bind-wallet.jpg
Labels: excellent

#345 task2: zpjayyy
  members/zpjayyy/task2/02_Blockchain_Basic.md
  members/zpjayyy/task2/bind-wallet.png
Labels: excellent

#387 task2: limsenkeat
  members/limsenkeat/task2/bind-wallet.jpg
  members/limsenkeat/task2/task2.md
Labels: excellent

#328 task2: jiantao88
  members/jiantao88/readme.md
  members/jiantao88/task2/bind-wallet.png
  members/jiantao88/task2/readme.md
Labels: bug

#414 task2: wmjchf
  members/wmjchf/task2/02_Blockchain_Basic.md
  members/wmjchf/task2/bind-wallet.jpg
Labels: excellent

#432 task2: HaisenCx
  members/HaisenCx/task2/02_Blockchain_Basic.md
  members/HaisenCx/task2/bind-wallet.png
Labels: excellent

#687 init:chanhohn
  members/chanhohn/readme.md
Labels: bug

#681 task1: qiaopengjun5162
  members/qiaopengjun5162/task1/image.png
  members/qiaopengjun5162/task1/react-to-do-list/.env.development
  members/qiaopengjun5162/task1/react-to-do-list/.eslintrc.cjs
  members/qiaopengjun5162/task1/react-to-do-list/.gitignore
  members/qiaopengjun5162/task1/react-to-do-list/README.md
  members/qiaopengjun5162/task1/react-to-do-list/index.html
  members/qiaopengjun5162/task1/react-to-do-list/package.json
  members/qiaopengjun5162/task1/react-to-do-list/pnpm-lock.yaml
  members/qiaopengjun5162/task1/react-to-do-list/postcss.config.js
  members/qiaopengjun5162/task1/react-to-do-list/src/App.scss
  members/qiaopengjun5162/task1/react-to-do-list/src/App.tsx
  members/qiaopengjun5162/task1/react-to-do-list/src/components/AddToDo.module.css
  members/qiaopengjun5162/task1/react-to-do-list/src/components/AddToDo.tsx
  members/qiaopengjun5162/task1/react-to-do-list/src/components/Header.module.css
  members/qiaopengjun5162/task1/react-to-do-list/src/components/Header.tsx
  members/qiaopengjun5162/task1/react-to-do-list/src/components/ToDoItem.module.css
  members/qiaopengjun5162/task1/react-to-do-list/src/components/ToDoItem.tsx
  members/qiaopengjun5162/task1/react-to-do-list/src/components/ToDoList.module.css
  members/qiaopengjun5162/task1/react-to-do-list/src/components/ToDoList.tsx
  members/qiaopengjun5162/task1/react-to-do-list/src/index.css
  members/qiaopengjun5162/task1/react-to-do-list/src/main.tsx
  members/qiaopengjun5162/task1/react-to-do-list/src/styles/sassConfig.scss
  members/qiaopengjun5162/task1/react-to-do-list/src/vite-env.d.ts
  members/qiaopengjun5162/task1/react-to-do-list/tailwind.config.js
  members/qiaopengjun5162/task1/react-to-do-list/tsconfig.json
  members/qiaopengjun5162/task1/react-to-do-list/tsconfig.node.json
  members/qiaopengjun5162/task1/react-to-do-list/vite.base.config.ts
  members/qiaopengjun5162/task1/react-to-do-list/vite.config.ts
  members/qiaopengjun5162/task1/react-to-do-list/vite.dev.config.ts
  members/qiaopengjun5162/task1/react-to-do-list/vite.prod.config.ts
  members/qiaopengjun5162/task1/readme.md
Labels: bug

#630 task2: Shuning0312
  members/Shuning0312/task2/bind-wallet.jpg
  members/Shuning0312/task2/blockDataStru.png
  members/Shuning0312/task2/blockchainStru.png
  members/Shuning0312/task2/task2.md
Labels: excellent

#639 task2: hu-qi
  members/hu-qi/task2/02_Blockchain_Basic.md
  members/hu-qi/task2/bind-wallet.jpg
Labels: excellent

#676 task2: 964674798
  members/964674798/task2/.bind-wallet.jpg.png
  members/964674798/task2/readme.md
Labels: excellent

#203 task2: veithly
  members/veithly/task2/02_Blockchain_Basic.md
  members/veithly/task2/bind-wallet.jpg
Labels: bug

#525 task2: vv1133
  members/vv1133/task2/02_Blockchain_Basic.md
  members/vv1133/task2/bind-wallet.jpg
Labels: bug

#742 add 钱包地址
  members/leon-kay/readme.md
Labels: bug

#632 Init: Joejo
  members/Joejo/readme.md
Labels: bug

#641 task2: Y2511525406
  members/Y2511525406/task2/bind-wallet.png
  members/Y2511525406/task2/readme.md
Labels: bug

#305 task2: barry
  members/haobarry/taks2/02_Blockchain_Basic.md
  members/haobarry/taks2/screenshot-wallet.png
Labels: bug

#760 init: zhong-shanfu
  members/github_id/readme.md
  members/zhong-shanfu/readme.md
Labels: bug

#771 task1:no5no6
  members/no5no6/task1/README.md
  members/no5no6/task1/index.html
  members/no5no6/task1/package.json
  members/no5no6/task1/pnpm-lock.yaml
  members/no5no6/task1/public/vite.svg
  members/no5no6/task1/src/App.tsx
  members/no5no6/task1/src/assets/react.svg
  members/no5no6/task1/src/components/addToDo/index.tsx
  members/no5no6/task1/src/components/header/index.tsx
  members/no5no6/task1/src/components/todoItem/index.tsx
  members/no5no6/task1/src/components/todoList/index.tsx
  members/no5no6/task1/src/main.tsx
  members/no5no6/task1/src/types/index.ts
  members/no5no6/task1/src/vite-env.d.ts
  members/no5no6/task1/tsconfig.json
  members/no5no6/task1/tsconfig.node.json
  members/no5no6/task1/uno.config.ts
  members/no5no6/task1/vite.config.ts
Labels: bug

#819 task2:liudafengshu
  members/liudafengshu/task2/02_Blockchain_Basic.md
  members/liudafengshu/task2/bind-wallet.jpg
Labels: bug

#843 init: douglas-ou
  members/douglas-ou/readme.md
Labels: bug

#887 task1:LyricaQiang
  members/LyricaQiang/task1/.eslintrc.cjs
  members/LyricaQiang/task1/.gitignore
  members/LyricaQiang/task1/README.md
  members/LyricaQiang/task1/index.html
  members/LyricaQiang/task1/package.json
  members/LyricaQiang/task1/pnpm-lock.yaml
  members/LyricaQiang/task1/public/vite.svg
  members/LyricaQiang/task1/src/App.css
  members/LyricaQiang/task1/src/App.jsx
  members/LyricaQiang/task1/src/assets/react.svg
  members/LyricaQiang/task1/src/components/add-to-do.jsx
  members/LyricaQiang/task1/src/components/header.jsx
  members/LyricaQiang/task1/src/components/to-do-item.jsx
  members/LyricaQiang/task1/src/components/to-do-list.jsx
  members/LyricaQiang/task1/src/index.css
  members/LyricaQiang/task1/src/main.jsx
  members/LyricaQiang/task1/vite.config.js
Labels: bug

#517 task1: JeremyZ
  members/warku123/readme.md
  members/warku123/task1/my-todo-app/.eslintrc.cjs
  members/warku123/task1/my-todo-app/.gitignore
  members/warku123/task1/my-todo-app/README.md
  members/warku123/task1/my-todo-app/index.html
  members/warku123/task1/my-todo-app/package-lock.json
  members/warku123/task1/my-todo-app/package.json
  members/warku123/task1/my-todo-app/public/vite.svg
  members/warku123/task1/my-todo-app/src/App.jsx
  members/warku123/task1/my-todo-app/src/assets/react.svg
  members/warku123/task1/my-todo-app/src/components/AddToDo.jsx
  members/warku123/task1/my-todo-app/src/components/Header.jsx
  members/warku123/task1/my-todo-app/src/components/ToDoItem.jsx
  members/warku123/task1/my-todo-app/src/components/ToDoList.jsx
  members/warku123/task1/my-todo-app/src/index.css
  members/warku123/task1/my-todo-app/src/main.jsx
  members/warku123/task1/my-todo-app/vite.config.js
  members/warku123/task2/bind-wallet.jpg
  members/warku123/task2/task2.md
Labels: bug

#912 init: bdingtech
  members/bdingtech/readme.md
Labels: bug

#905 task1:KeyHMX
  members/KeyHMX/task1/todoList/.eslintrc.cjs
  members/KeyHMX/task1/todoList/.gitignore
  members/KeyHMX/task1/todoList/README.md
  members/KeyHMX/task1/todoList/image.png
  members/KeyHMX/task1/todoList/index.html
  members/KeyHMX/task1/todoList/package-lock.json
  members/KeyHMX/task1/todoList/package.json
  members/KeyHMX/task1/todoList/public/vite.svg
  members/KeyHMX/task1/todoList/src/App.css
  members/KeyHMX/task1/todoList/src/App.jsx
  members/KeyHMX/task1/todoList/src/assets/react.svg
  members/KeyHMX/task1/todoList/src/components/AddToDo/index.jsx
  members/KeyHMX/task1/todoList/src/components/Header/index.jsx
  members/KeyHMX/task1/todoList/src/components/Header/style.css
  members/KeyHMX/task1/todoList/src/components/ToDoItem/index.jsx
  members/KeyHMX/task1/todoList/src/components/ToDoList/index.jsx
  members/KeyHMX/task1/todoList/src/index.css
  members/KeyHMX/task1/todoList/src/main.jsx
  members/KeyHMX/task1/todoList/vite.config.js
Labels: bug
