Repository openbuildxyz/Web3-Frontend-Bootcamp, pull requests merged in 2024-07, with the labels that each got.

#944 task3: zhangloveyan
  members/zhangloveyan/task3/NFTMarket.sol
  members/zhangloveyan/task3/ShouHuNFT.sol
  members/zhangloveyan/task3/ShouHuToken.sol
  members/zhangloveyan/task3/readme.md
Labels: excellent

#800 task3: flexibility2
  members/flexibility2/task3/NFTExchange.sol
  members/flexibility2/task3/OpenBuildToken.sol
  members/flexibility2/task3/Web3FrontendToken.sol
  members/flexibility2/task3/readme.md
Labels: excellent

#795 task3:choizhang
  members/choizhang/task3/03_NFTMarket_Contract.md
  members/choizhang/task3/Metadata/nft1.json
  members/choizhang/task3/contracts/ERC20.sol
  members/choizhang/task3/contracts/ERC721.sol
  members/choizhang/task3/contracts/NFTMarketplace.sol
  members/choizhang/task3/image.png
Labels: excellent

#595 task2: YinYang
  members/CipherYin/task2/02_Blockchain_Basic.md
  members/CipherYin/task2/bind-wallet.jpg
Labels: bug

#604 task2: sunnydreamer
  members/sunnydreamer/task2/02_Blockchain_Basic.md
  members/sunnydreamer/task2/bind-wallet.jpg
Labels: bug

#230 task2: TomatoDroid
  members/TomatoDroid/task2/02_Blockchain_Basic.md
  members/TomatoDroid/task2/bind-wallet.jpg
Labels: bug

#529 task2: Mika-Lahtinen
  members/Mika-Lahtinen/task2/Blockchain_Basic.md
  members/Mika-Lahtinen/task2/bind-wallet.png
Labels: bug

#1082 task7:hwwang2
  members/hwwang2/task7/aspect.jpg
  members/hwwang2/task7/readme.md
  members/hwwang2/task7/throttler-aspect/.gitignore
  members/hwwang2/task7/throttler-aspect/README.md
  members/hwwang2/task7/throttler-aspect/README.zh.md
  members/hwwang2/task7/throttler-aspect/asconfig.json
  members/hwwang2/task7/throttler-aspect/aspect/index.ts
  members/hwwang2/task7/throttler-aspect/aspect/tsconfig.json
  members/hwwang2/task7/throttler-aspect/contracts/counter.sol
  members/hwwang2/task7/throttler-aspect/package-lock.json
  members/hwwang2/task7/throttler-aspect/package.json
  members/hwwang2/task7/throttler-aspect/project.config.json
  members/hwwang2/task7/throttler-aspect/scripts/aspect-deploy.cjs
  members/hwwang2/task7/throttler-aspect/scripts/batch-test.cjs
  members/hwwang2/task7/throttler-aspect/scripts/bind.cjs
  members/hwwang2/task7/throttler-aspect/scripts/contract-call.cjs
  members/hwwang2/task7/throttler-aspect/scripts/contract-deploy.cjs
  members/hwwang2/task7/throttler-aspect/scripts/contract-send.cjs
  members/hwwang2/task7/throttler-aspect/scripts/create-account.cjs
  members/hwwang2/task7/throttler-aspect/scripts/get-bound-account.cjs
  members/hwwang2/task7/throttler-aspect/scripts/get-bound-aspect.cjs
  members/hwwang2/task7/throttler-aspect/scripts/operation.cjs
  members/hwwang2/task7/throttler-aspect/scripts/unbind.cjs
Labels: bug

#1097 task7: keyding
  members/keyding/task7/aspect/index.ts
Labels: bug

#1004 task8:gunksd
  members/gunksd/task8/link.md
  members/gunksd/task8/截图.png
Labels: bug

#1112 feat: xiangnuans
  members/xiangnuans/task8/readme.md
  members/xiangnuans/task8/verify.jpg
Labels: bug

#302 task2: huzhengen
  members/huzhengen/task2/bind-wallet.jpg
  members/huzhengen/task2/readme.md
Labels: bug

#515 task1: Mika-Lahtinen
  members/Mika-Lahtinen/task1/homework_pics.md
  members/Mika-Lahtinen/task1/note.md
  members/Mika-Lahtinen/task1/pic/初始化.png
  members/Mika-Lahtinen/task1/pic/删除.png
  members/Mika-Lahtinen/task1/pic/完成.png
  members/Mika-Lahtinen/task1/pic/新建条目.png
  members/Mika-Lahtinen/task1/todolist/.eslintrc.cjs
  members/Mika-Lahtinen/task1/todolist/.gitignore
  members/Mika-Lahtinen/task1/todolist/index.html
  members/Mika-Lahtinen/task1/todolist/package.json
  members/Mika-Lahtinen/task1/todolist/public/vite.svg
  members/Mika-Lahtinen/task1/todolist/src/App.css
  members/Mika-Lahtinen/task1/todolist/src/App.tsx
  members/Mika-Lahtinen/task1/todolist/src/assets/react.svg
  members/Mika-Lahtinen/task1/todolist/src/components/AddTodo.tsx
  members/Mika-Lahtinen/task1/todolist/src/components/Header.tsx
  members/Mika-Lahtinen/task1/todolist/src/components/TodoItem.tsx
  members/Mika-Lahtinen/task1/todolist/src/components/TodoList.tsx
  members/Mika-Lahtinen/task1/todolist/src/index.css
  members/Mika-Lahtinen/task1/todolist/src/main.tsx
  members/Mika-Lahtinen/task1/todolist/src/vite-env.d.ts
  members/Mika-Lahtinen/task1/todolist/tsconfig.json
  members/Mika-Lahtinen/task1/todolist/tsconfig.node.json
  members/Mika-Lahtinen/task1/todolist/vite.config.ts
  members/zpjayyy/task1/to-do-list/package-lock.json
Labels: bug

#1143 task1:WonderfulWan8
  members/WonderfulWan8/task1/ScreenShot.png
  members/WonderfulWan8/task1/my-todo-app/.eslintrc.cjs
  members/WonderfulWan8/task1/my-todo-app/.gitignore
  members/WonderfulWan8/task1/my-todo-app/README.md
  members/WonderfulWan8/task1/my-todo-app/Snipaste_2024-07-06_20-51-52.png
  members/WonderfulWan8/task1/my-todo-app/index.html
  members/WonderfulWan8/task1/my-todo-app/package-lock.json
  members/WonderfulWan8/task1/my-todo-app/package.json
  members/WonderfulWan8/task1/my-todo-app/public/vite.svg
  members/WonderfulWan8/task1/my-todo-app/src/App.css
  members/WonderfulWan8/task1/my-todo-app/src/App.tsx
  members/WonderfulWan8/task1/my-todo-app/src/assets/react.svg
  members/WonderfulWan8/task1/my-todo-app/src/components/AddToDo.tsx
  members/WonderfulWan8/task1/my-todo-app/src/components/Header.tsx
  members/WonderfulWan8/task1/my-todo-app/src/components/ToDoItem.tsx
  members/WonderfulWan8/task1/my-todo-app/src/components/ToDoList.tsx
  members/WonderfulWan8/task1/my-todo-app/src/index.css
  members/WonderfulWan8/task1/my-todo-app/src/main.tsx
  members/WonderfulWan8/task1/my-todo-app/src/vite-env.d.ts
  members/WonderfulWan8/task1/my-todo-app/tsconfig.app.json
  members/WonderfulWan8/task1/my-todo-app/tsconfig.json
  members/WonderfulWan8/task1/my-todo-app/tsconfig.node.json
  members/WonderfulWan8/task1/my-todo-app/vite.config.ts
Labels: bug

#865 task3: anderfib
  members/anderfib/task3/ERC20_ATK.sol
  members/anderfib/task3/ERC721_NTF.sol
  members/anderfib/task3/NFTMarket.sol
  members/anderfib/task3/reademe.md
Labels: bug

#1174 task9: flytam
  members/flytam/task9/readme.md
  members/flytam/task9/sepolia-xxxx/.gitignore
  members/flytam/task9/sepolia-xxxx/abis/NFTMarket.json
  members/flytam/task9/sepolia-xxxx/docker-compose.yml
  members/flytam/task9/sepolia-xxxx/networks.json
  members/flytam/task9/sepolia-xxxx/package.json
  members/flytam/task9/sepolia-xxxx/schema.graphql
  members/flytam/task9/sepolia-xxxx/src/nft-market.ts
  members/flytam/task9/sepolia-xxxx/subgraph.yaml
  members/flytam/task9/sepolia-xxxx/tests/nft-market-utils.ts
  members/flytam/task9/sepolia-xxxx/tests/nft-market.test.ts
  members/flytam/task9/sepolia-xxxx/tsconfig.json
Labels: bug

#752 Task2: FrankChencc
  members/FrankChencc/task2/02_Blockchain_Basic.md
  members/FrankChencc/task2/bind-wallet.jpg
Labels: bug

#633 task1: Joejo
  members/Joejo/task1/TodoList/.eslintrc.cjs
  members/Joejo/task1/TodoList/.gitignore
  members/Joejo/task1/TodoList/README.md
  members/Joejo/task1/TodoList/index.html
  members/Joejo/task1/TodoList/package.json
  members/Joejo/task1/TodoList/pnpm-lock.yaml
  members/Joejo/task1/TodoList/public/vite.svg
  members/Joejo/task1/TodoList/src/AddToDo.tsx
  members/Joejo/task1/TodoList/src/App.css
  members/Joejo/task1/TodoList/src/App.tsx
  members/Joejo/task1/TodoList/src/Empty.tsx
  members/Joejo/task1/TodoList/src/Header.tsx
  members/Joejo/task1/TodoList/src/TodoItem.tsx
  members/Joejo/task1/TodoList/src/TodoList.tsx
  members/Joejo/task1/TodoList/src/assets/react.svg
  members/Joejo/task1/TodoList/src/index.css
  members/Joejo/task1/TodoList/src/main.tsx
  members/Joejo/task1/TodoList/src/vite-env.d.ts
  members/Joejo/task1/TodoList/tsconfig.json
  members/Joejo/task1/TodoList/tsconfig.node.json
  members/Joejo/task1/TodoList/vite.config.ts
  members/Joejo/task1/TodoList/yarn.lock
  members/Joejo/task1/package.json
Labels: bug

#401 task2: liyincode
  members/liyincode/readme.md
  members/liyincode/task2/02_Blockchain_Basic.md
  members/liyincode/task2/bind-wallet.png
Labels: bug

#1199 task9: linghuccc
  members/linghuccc/task9/readme.md
  members/linghuccc/task9/subgraph.png
Labels: bug

#1205 task9: aliyan404
  members/aliyan404/task9/task 9.md
  members/aliyan404/task9/子图截图.jpg
Labels: bug

#1127 task3: posuihushui
  .gitignore
  members/posuihushui/task3/README.md
  members/posuihushui/task3/contracts/MyNFT.sol
  members/posuihushui/task3/contracts/MyToken.sol
  members/posuihushui/task3/contracts/NFTMarket.sol
  members/posuihushui/task3/hardhat.config.ts
  members/posuihushui/task3/package-lock.json
  members/posuihushui/task3/package.json
  members/posuihushui/task3/test/Lock.ts
  members/posuihushui/task3/tsconfig.json
Labels: bug

#998 task2: joy-joy-joy-joy-joy-joy-joy
  members/joy-joy-joy-joy-joy-joy-joy/task2/02_Blockchain_Basic.md
  members/joy-joy-joy-joy-joy-joy-joy/task2/bind-wallet.jpg
Labels: invalid

#1193 task8: zhouBoom
  members/zhouBoom/task8/readme.md
  members/zhouBoom/task8/合约部署.png
  members/zhouBoom/task8/验证截图.png
Labels: bug

#1291 task8: zhouBoom
  members/zhouBoom/task8/readme.md
  members/zhouBoom/task8/合约验证.png
Labels: bug

#1296 task9: zhangolve
  members/zhangolve/task9/1.jpg
  members/zhangolve/task9/2.jpg
  members/zhangolve/task9/3.jpg
  members/zhangolve/task9/README.md
Labels: bug

#1272 task7:choizhang
  members/choizhang/task7/index.ts
  members/choizhang/task7/readme.md
  members/choizhang/task7/screenshot.png
Labels: bug

#1306 init:lsPrivateGit
  members/lsPrivateGit/readme.md
Labels: bug

#1297 task9: veithly
  members/veithly/task9/README.md
  members/veithly/task9/subgraph.png
  members/veithly/task9/subgraph2.png
  members/veithly/task9/subgraph3.jpeg
Labels: bug

#1243 task9：threshermagnus484159
  members/threshermagnus484159/task9/readme.md
  members/threshermagnus484159/task9/thegraph.png
  members/threshermagnus484159/task9/截图.png
Labels: bug

#1260 task1:Dr-yellow
  members/Dr-yellow/task1/web3_wallet/.eslintrc.cjs
  members/Dr-yellow/task1/web3_wallet/.gitignore
  members/Dr-yellow/task1/web3_wallet/README.md
  members/Dr-yellow/task1/web3_wallet/index.html
  members/Dr-yellow/task1/web3_wallet/package-lock.json
  members/Dr-yellow/task1/web3_wallet/package.json
  members/Dr-yellow/task1/web3_wallet/postcss.config.js
  members/Dr-yellow/task1/web3_wallet/public/vite.svg
  members/Dr-yellow/task1/web3_wallet/src/App.scss
  members/Dr-yellow/task1/web3_wallet/src/App.tsx
  members/Dr-yellow/task1/web3_wallet/src/assets/react.svg
  members/Dr-yellow/task1/web3_wallet/src/components/AddBtnToDo.tsx
  members/Dr-yellow/task1/web3_wallet/src/components/Header.tsx
  members/Dr-yellow/task1/web3_wallet/src/components/ToDoItem.tsx
  members/Dr-yellow/task1/web3_wallet/src/components/ToDoList.tsx
  members/Dr-yellow/task1/web3_wallet/src/index.scss
  members/Dr-yellow/task1/web3_wallet/src/main.tsx
  members/Dr-yellow/task1/web3_wallet/src/typings/index.d.ts
  members/Dr-yellow/task1/web3_wallet/src/vite-env.d.ts
  members/Dr-yellow/task1/web3_wallet/tailwind.config.js
  members/Dr-yellow/task1/web3_wallet/tsconfig.app.json
  members/Dr-yellow/task1/web3_wallet/tsconfig.json
  members/Dr-yellow/task1/web3_wallet/tsconfig.node.json
  members/Dr-yellow/task1/web3_wallet/vite.config.ts
  members/Dr-yellow/task1/web3_wallet/yarn.lock
Labels: invalid

#1318 task7: DeJeune
  members/DeJeune/task7/index.ts
  members/DeJeune/task7/readme.md
Labels: bug

#1261 task2:Dr-yellow
  members/Dr-yellow/task2/02_Blockchain_Basic.md
  members/Dr-yellow/task2/bind_wallet.jpg
Labels: bug

#1320 task9: DeJeune
  members/DeJeune/task9/image-1.png
  members/DeJeune/task9/image-2.png
  members/DeJeune/task9/image.png
  members/DeJeune/task9/readme.md
Labels: bug

#1344 task1: 0xsuxin
  members/0xsuxin/task1/README.md
  members/0xsuxin/task1/index.html
  members/0xsuxin/task1/package.json
  members/0xsuxin/task1/postcss.config.js
  members/0xsuxin/task1/renovate.json
  members/0xsuxin/task1/src/components/Header/index.tsx
  members/0xsuxin/task1/src/components/ToDoItem/index.tsx
  members/0xsuxin/task1/src/components/ToDoList/index.tsx
  members/0xsuxin/task1/src/components/root/App.tsx
  members/0xsuxin/task1/src/components/root/Main.tsx
  members/0xsuxin/task1/src/components/router/Router.tsx
  members/0xsuxin/task1/src/favicon.svg
  members/0xsuxin/task1/src/index.css
  members/0xsuxin/task1/src/lib/firebase.ts
  members/0xsuxin/task1/src/logo.svg
  members/0xsuxin/task1/src/main.tsx
  members/0xsuxin/task1/src/styles/arrow.css
  members/0xsuxin/task1/src/vite-env.d.ts
  members/0xsuxin/task1/tailwind.config.js
  members/0xsuxin/task1/tsconfig.json
  members/0xsuxin/task1/vite.config.ts
Labels: bug
